### PR TITLE
use scala.xml.Utility to escape strings

### PR DESCRIPTION
**Pull request by darl**

### CODE REVIEW

**Comment by borkaehw** [comment]
Thanks for the suggestion! Could you fix the formatting so we can move forward?

If you don't mind, I am also happy to fix it.

**Comment by darl** [comment]
I created PR from github ui so I didn't run any lint locally.
You can fix it yourself or I will fix it tomorrow.

**Comment by borkaehw** [comment]
It doesn't seem urgent, I can wait until tomorrow.

Or, I suppose you have to give me permission to fix this PR. Instructions here.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Either way works for me.

**Comment by borkaehw** [comment]
Never mind, you have enabled it. Fixing it now. Thanks again.

**Pull request merged**
